name: finpac_service_report
description: Aplikasi Service Report PT. Finpac Anugerah Indonesia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
  signature: ^5.4.0
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.11.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo_finpac.png
    - assets/logo_aplikasi.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true                   # <--- TAMBAHKAN BARIS INI UNTUK IPHONE
  image_path: "assets/icon.png"
  min_sdk_android: 21